modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="pirates"
version="1.0.0"
displayName="Pirates"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Caleb Schouten, MCreator"

[[dependencies.pirates]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



